#!/usr/bin/env bash
# Install a Postgres server for Faberon without sudo (e.g. on a cluster login node).
#
# This only installs the server, it does not create the faberon database:
# after you start Postgres, run scripts/create-faberon-db.sh for that.
#
# Usage: scripts/install-postgres-no-sudo.sh
#
# Optional env:
#   FABERON_PG_PREFIX   install root (default: $HOME/faberon/postgres)
#   FABERON_PG_PORT     listen port (default: 54329)
#   FABERON_PG_VERSION  binary release version (default: 16.15.0)

set -euo pipefail

prefix="${FABERON_PG_PREFIX:-$HOME/faberon/postgres}"
port="${FABERON_PG_PORT:-54329}"
version="${FABERON_PG_VERSION:-16.15.0}"
target="x86_64-unknown-linux-gnu"
archive="postgresql-${version}-${target}.tar.gz"
url="https://github.com/theseus-rs/postgresql-binaries/releases/download/${version}/${archive}"

data="$prefix/data"
log_dir="$prefix/log"
run_dir="$prefix/run"
env_file="${XDG_CONFIG_HOME:-$HOME/.config}/faberon/postgres.env"

if [ "$(uname -m)" != "x86_64" ]; then
    echo "error: only x86_64 binaries are wired up (got $(uname -m))" >&2
    echo "set FABERON_PG_PREFIX to an existing install, or extend this script" >&2
    exit 1
fi

mkdir -p "$prefix" "$log_dir" "$run_dir"
mkdir -p "$(dirname "$env_file")"

if [ ! -x "$prefix/bin/postgres" ]; then
    echo ">> downloading $archive"
    tmp="$(mktemp -d)"
    # shellcheck disable=SC2064
    trap 'rm -rf "$tmp"' EXIT
    curl -fL --retry 3 -o "$tmp/$archive" "$url"
    echo ">> unpacking into $prefix"
    tar -xzf "$tmp/$archive" -C "$tmp"
    # Archive root is postgresql-$version-$target/; move its contents into $prefix.
    src="$tmp/postgresql-${version}-${target}"
    # Copy rather than move across filesystems
    cp -a "$src"/. "$prefix"/
    rm -rf "$tmp"
    trap - EXIT
else
    echo ">> binaries already present at $prefix/bin"
fi

if [ ! -f "$data/PG_VERSION" ]; then
    echo ">> initdb $data"
    "$prefix/bin/initdb" \
        -D "$data" \
        --username="$USER" \
        --auth-local=trust \
        --auth-host=trust \
        --no-instructions
    {
        echo
        echo "# Faberon no-sudo install overrides"
        echo "listen_addresses = 'localhost'"
        echo "port = $port"
        echo "unix_socket_directories = '$run_dir'"
    } >>"$data/postgresql.conf"
else
    echo ">> data directory already initialised at $data"
fi

db_url="postgres://localhost:${port}/faberon"

cat >"$env_file" <<EOF
# Generated by scripts/install-postgres-no-sudo.sh. Source before using Faberon.
export PATH="$prefix/bin:\$PATH"
export FABERON_PG_PREFIX="$prefix"
export FABERON_PGDATA="$data"
export PGDATA="$data"
export PGHOST=localhost
export PGPORT=$port
export FABERON_DATABASE_URL="$db_url"
EOF

cat <<EOF

Postgres (no-sudo install) is ready.

  install:  $prefix
  data:     $data
  env file: $env_file

To start it:

    source $env_file
    pg_ctl -D "\$FABERON_PGDATA" -l "$log_dir/pg.log" start

Once (with Postgres running, from the Faberon repo root):

    scripts/create-faberon-db.sh

To stop it:

    pg_ctl -D "\$FABERON_PGDATA" stop

Note: PGDATA lives on the same filesystem as \$HOME. On login nodes that is
often a network FS (e.g. Weka). Fine for Faberon's small ledger; do not put
a heavy production DB here.
EOF
