#!/usr/bin/env bash
# Install a Postgres server for Faberon without sudo (e.g. on a cluster login node).
#
# This only installs the server, it does not create the faberon database:
# after you start Postgres, run scripts/create-faberon-db.sh for that.
#
# Optional env:
#   FABERON_PG_PREFIX   install root (default: $HOME/faberon/postgres)
#   FABERON_PG_PORT     listen port (default: 54329)
#   FABERON_PG_VERSION  binary release version (default: 16.15.0)

set -euo pipefail

prefix="${FABERON_PG_PREFIX:-$HOME/faberon/postgres}"
port="${FABERON_PG_PORT:-54329}"
version="${FABERON_PG_VERSION:-16.15.0}"
target="x86_64-unknown-linux-gnu"
archive="postgresql-${version}-${target}.tar.gz"
url="https://github.com/theseus-rs/postgresql-binaries/releases/download/${version}/${archive}"
# DBOS runs CREATE EXTENSION "uuid-ossp". The theseus uuid-ossp.so needs
# libossp-uuid.so.16, which many login nodes do not ship. Vendor it.
ossp_deb_url="http://archive.ubuntu.com/ubuntu/pool/universe/o/ossp-uuid/libossp-uuid16_1.6.2-1.5build13_amd64.deb"

data="$prefix/data"
log_dir="$prefix/log"
run_dir="$prefix/run"
lib_dir="$prefix/lib"
env_file="${XDG_CONFIG_HOME:-$HOME/.config}/faberon/postgres.env"

ensure_libossp_uuid() {
    # uuid-ossp.so (shipped with the binaries) links against libossp-uuid.so.16.
    if [ -e "$lib_dir/libossp-uuid.so.16" ]; then
        echo ">> libossp-uuid.so.16 already in $lib_dir"
        return
    fi
    for candidate in \
        /lib/x86_64-linux-gnu/libossp-uuid.so.16 \
        /usr/lib/x86_64-linux-gnu/libossp-uuid.so.16 \
        /lib64/libossp-uuid.so.16; do
        if [ -e "$candidate" ]; then
            echo ">> copying $candidate into $lib_dir"
            cp -a "$candidate" "$lib_dir/"
            # Real file behind a symlink, if any.
            if [ -L "$candidate" ]; then
                real="$(readlink -f "$candidate")"
                cp -a "$real" "$lib_dir/"
            fi
            return
        fi
    done
    echo ">> downloading libossp-uuid (needed by uuid-ossp for DBOS)"
    tmp="$(mktemp -d)"
    # shellcheck disable=SC2064
    trap 'rm -rf "$tmp"' EXIT
    curl -fL --retry 3 -o "$tmp/libossp-uuid.deb" "$ossp_deb_url"
    dpkg-deb -x "$tmp/libossp-uuid.deb" "$tmp/root"
    so="$(find "$tmp/root" -name 'libossp-uuid.so.16' | head -1)"
    if [ -z "$so" ]; then
        echo "error: libossp-uuid.so.16 not found inside the downloaded package" >&2
        exit 1
    fi
    cp -a "$(dirname "$so")"/libossp-uuid.so.16* "$lib_dir/"
    rm -rf "$tmp"
    trap - EXIT
}

if [ "$(uname -m)" != "x86_64" ]; then
    echo "error: only x86_64 binaries are wired up (got $(uname -m))" >&2
    echo "set FABERON_PG_PREFIX to an existing install, or extend this script" >&2
    exit 1
fi

mkdir -p "$prefix" "$log_dir" "$run_dir" "$lib_dir"
mkdir -p "$(dirname "$env_file")"

if [ ! -x "$prefix/bin/postgres" ]; then
    echo ">> downloading $archive"
    tmp="$(mktemp -d)"
    # shellcheck disable=SC2064
    trap 'rm -rf "$tmp"' EXIT
    curl -fL --retry 3 -o "$tmp/$archive" "$url"
    echo ">> unpacking into $prefix"
    tar -xzf "$tmp/$archive" -C "$tmp"
    # Archive root is postgresql-$version-$target/; move its contents into $prefix.
    src="$tmp/postgresql-${version}-${target}"
    # Copy rather than move across filesystems
    cp -a "$src"/. "$prefix"/
    rm -rf "$tmp"
    trap - EXIT
else
    echo ">> binaries already present at $prefix/bin"
fi

ensure_libossp_uuid

if [ ! -f "$data/PG_VERSION" ]; then
    echo ">> initdb $data"
    "$prefix/bin/initdb" \
        -D "$data" \
        --username="$USER" \
        --auth-local=trust \
        --auth-host=trust \
        --no-instructions
    {
        echo
        echo "# Faberon no-sudo install overrides"
        echo "listen_addresses = 'localhost'"
        echo "port = $port"
        echo "unix_socket_directories = '$run_dir'"
    } >>"$data/postgresql.conf"
else
    echo ">> data directory already initialised at $data"
fi

db_url="postgres://localhost:${port}/faberon"

cat >"$env_file" <<EOF
# Generated by scripts/install-postgres-no-sudo.sh. Source before using Faberon.
export PATH="$prefix/bin:\$PATH"
export LD_LIBRARY_PATH="$lib_dir\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
export FABERON_PG_PREFIX="$prefix"
export FABERON_PGDATA="$data"
export PGDATA="$data"
export PGHOST=localhost
export PGPORT=$port
export FABERON_DATABASE_URL="$db_url"
EOF

cat <<EOF

Postgres (no-sudo install) is ready.

  install:  $prefix
  data:     $data
  env file: $env_file

To start it:

    source $env_file
    pg_ctl -D "\$FABERON_PGDATA" -l "$log_dir/pg.log" start

Once (with Postgres running, from the Faberon repo root):

    bash scripts/create-faberon-db.sh

To stop it:

    pg_ctl -D "\$FABERON_PGDATA" stop

Note: PGDATA lives on the same filesystem as \$HOME. On login nodes that is
often a network FS (e.g. Weka). Fine for Faberon's small ledger; do not put
a heavy production DB here.
EOF
